version: '3.8'

services:
  task-tracker:
    build:
      context: .
      args:
        VERSION: ${VERSION:-0.0.0}
    ports:
      - "3002:3002"
    restart: unless-stopped
    container_name: task-tracker-app
    environment:
      - NODE_ENV=production
      - APP_VERSION=${VERSION:-0.0.0}
    volumes:
      - task-tracker-data:/app/server/data

volumes:
  task-tracker-data:
    name: task-tracker-data
