version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: total_task
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
