name: Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        id: format_check
        run: npm run format:check
        continue-on-error: true

      - name: Auto fix formatting
        if: steps.format_check.outcome == 'failure'
        run: npm run format

      - name: Verify formatting
        if: steps.format_check.outcome == 'failure'
        run: npm run format:check
